### ISSUE TITLE
Parallel Ledger account overwrite Polkadot Ledger accounts on Polkadot-JS UI and the Polkadot extension

### ISSUE THREAD

**Issue by Juanma0x** [Zondax/ledger-parallel#21]
To replicate this scenario, follow the steps below:

1. Install the Polkadot Ledger app with version 23.9420.2.
2. Install the developer version of the Parallel Ledger app, specifically version 17.189.9.
3. Add the Polkadot Ledger account to either the [Polkadot-JS UI](https://polkadot.js.org/apps/), or use the [Polkadot extension](https://polkadot.js.org/extension/).
4. Next, add the Parallel Ledger account.

The outcome of these steps is as follows:

- Polkadot-JS UI or the Polkadot extension will display the Parallel Ledger account while the Polkadot Ledger account will no longer be visible.
- Conversely, if the Polkadot Ledger account is added, the Parallel Ledger account will disappear.

Desired outcome:
- Both accounts should be able to be added to either Polkadot-JS UI and the Polkadot extension, coexisting.

:link: [zboto Link](https://app.clickup.com/t/861n1qqcj)

**Comment by ftheirs** [comment]
Hi @Juanma0x, we are not longer maintaining Parallel app but I can tell you that this is an UI/UX issue and the app is ok. Since Parallel and Polkadot use the same derivation path, the pubkey is the same and probable polkadot-js just detects that and doesn't compare the addresses.
I'm closing this issue and probably you need to report this here: https://github.com/polkadot-js
